### ISSUE TITLE
Load custom exporter grafana dashboards

### ISSUE THREAD

**Issue by theodore86** [theodore86/github-rate-limits-exporter#237]
ConfigMap (list) to load custom grafana dashboards if available for the github rate limits exporter.

1. Update values.yml to include labels and annotations for the grafana operator

```yaml
# Integration with Grafana operator
grafanaLabels: {}

grafanaAnnotations: {}
```

2. Update templates with configMapList to automatically load grafana dashboards (if available under dashboards folder)
